server:
  error:
    include-message: always

spring:
  application:
    name: java-mentoring-adv-3
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url=jdbc: h2:file:~/jmp-adv-3
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
#    show-sql: true
